### ISSUE TITLE
Logs filled up my disk for the second time

### ISSUE THREAD

**Issue by rwjack** [ActivityWatch/aw-watcher-window#87]
https://github.com/ActivityWatch/aw-server/issues/101

it may belong here actually

**Comment by BelKed** [comment]
Are you using the latest version? Seems like the error was fixed some time ago:
- https://github.com/ActivityWatch/aw-core/pull/114

---

By the way, please, close the other issue to prevent duplicates :)

**Comment by rwjack** [comment]
I'm running v0.12.0

Do you think the issue belongs here? If so, I can close the other one.

**Comment by BelKed** [comment]
• `v0.12.0` was released on **Aug 31, 2022**
• The mentioned PR with the fix was merged to `master` on **Oct 26, 2022**

So, the `v0.12.0` doesn't have the fixed code.

---

Please, use the latest version. Ideally, the beta one ([`v0.12.2b1`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.2b1)), as the "stable" ([`v0.12.1`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.1)) has some bugs.
If the problem still persists, feel free to let us know ;)

---

And, yup, I think the issue belongs here :)

**Comment by rwjack** [comment]
Figures, thanks for the info. Guessing this one can be closed too if it's fixed in v0.12.1

**Comment by BelKed** [comment]
You're welcome :) And, I think yes, feel free to close this issue...
